<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class Indikator extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
            $indikators = [
        [
            'id' => '5',
            'nama_indikator' => 'Waktu Tunggu Rawat Jalan',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '7',
            'kamus_indikator_id' => '5',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '6',
            'nama_indikator' => 'Penundaan Operasi Elektif',
            'target_indikator' => '5.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '27',
            'kamus_indikator_id' => '6',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '7',
            'nama_indikator' => 'Kepatuhan Waktu Visite Dokter',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '45',
            'kamus_indikator_id' => '7',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '15',
            'nama_indikator' => 'Tidak ada kesalahan Pemberian Obat di Rawat Inap',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '45',
            'kamus_indikator_id' => '15',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '16',
            'nama_indikator' => 'Tidak ada kesalahan memasukan obat ke plastik etiket pasien lain di Farmasi',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '21',
            'kamus_indikator_id' => '16',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '17',
            'nama_indikator' => 'Tidak ada kesalahan input hasil expertise Radiologi oleh Radiografer ke E-MR',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '34',
            'kamus_indikator_id' => '17',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '18',
            'nama_indikator' => 'Tidak ada kesalahan pemberian obat pulang pasien rawat inap',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '45',
            'kamus_indikator_id' => '18',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '19',
            'nama_indikator' => 'Kepatuhan Verifikasi SBAR instruksi via telepon di Rawat Inap',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '45',
            'kamus_indikator_id' => '19',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '23',
            'nama_indikator' => 'Tidak ada kejadian Pasien Jatuh di Area Layanan',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '50',
            'kamus_indikator_id' => '23',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '26',
            'nama_indikator' => 'kesesuaian waktu tunggu pemulangan pasien rawat inap < 2 jam',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '45',
            'kamus_indikator_id' => '26',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '27',
            'nama_indikator' => 'Maternity : Ketepatan Waktu Operasi SC Elektif < 45 menit sesuai jadwal',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '27',
            'kamus_indikator_id' => '27',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '30',
            'nama_indikator' => 'Waktu tunggu hasil expertise Radiologi (Foto Thorax < 3 jam, USG < 60 Menit, CT Scan < 6 Jam',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '34',
            'kamus_indikator_id' => '30',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '31',
            'nama_indikator' => 'Respon Time Menjawab Permintaan Rujukan Melalui Sistem Rujukan',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '18',
            'kamus_indikator_id' => '31',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '33',
            'nama_indikator' => 'Kepatuhan Perawat Melakukan TTV dan Penginputan di ERM',
            'target_indikator' => '95.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '7',
            'kamus_indikator_id' => '33',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '34',
            'nama_indikator' => 'Angka Kepatuhan Jam Praktek Dokter Spesialis Sesuai Jadwal',
            'target_indikator' => '90.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '7',
            'kamus_indikator_id' => '34',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '37',
            'nama_indikator' => 'Tidak Ada Kesalahan Pemberian Alergen pada Pasien Alergi di Rawat Inap',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '45',
            'kamus_indikator_id' => '37',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '39',
            'nama_indikator' => 'Kepatuhan Pengisian Partograf pada Persalinan Kala I Fase Aktif',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '44',
            'kamus_indikator_id' => '39',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '40',
            'nama_indikator' => 'Tidak Ada Kesalahan Penempelan Stiker Pasien KKebidanan di VK',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '44',
            'kamus_indikator_id' => '40',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '41',
            'nama_indikator' => 'Readmission Rate ≤ 30 Hari',
            'target_indikator' => '5.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '26',
            'kamus_indikator_id' => '41',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '42',
            'nama_indikator' => 'Kepatuhan Klaim INA-CBGs',
            'target_indikator' => '95.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '26',
            'kamus_indikator_id' => '42',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '43',
            'nama_indikator' => 'Case Mix Index (CMI)',
            'target_indikator' => '1.20',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '26',
            'kamus_indikator_id' => '43',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '51',
            'nama_indikator' => 'Keterlambatan Waktu Mulai Operasi >30 Menit',
            'target_indikator' => '2.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '27',
            'kamus_indikator_id' => '51',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '52',
            'nama_indikator' => 'Tidak Ada Kesalahan Penjadwalan Tindakan Operasi',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '27',
            'kamus_indikator_id' => '52',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '54',
            'nama_indikator' => 'Tidak adanya Kesalahan dalam proses packing dan labeling',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '27',
            'kamus_indikator_id' => '54',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '55',
            'nama_indikator' => 'Tidak adanya kerusakan kemasan setelah post sterilisasi',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '27',
            'kamus_indikator_id' => '55',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '56',
            'nama_indikator' => 'Kepatuhan pengisian formulir permintaan sterilisasi',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '27',
            'kamus_indikator_id' => '56',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '57',
            'nama_indikator' => 'Ketepatan kemasan alat medis dan linen steril sesuai perubahan warna indicator post sterilisasi',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '27',
            'kamus_indikator_id' => '57',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '59',
            'nama_indikator' => 'Pemenuhan Waktu Tunggu Rontgen Thorax <= 3 Jam',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '34',
            'kamus_indikator_id' => '59',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '60',
            'nama_indikator' => 'Tidak Ada Kesalahan Pemberian Hasil Laboratorium Pasien Lain',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '8',
            'kamus_indikator_id' => '60',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '45',
            'nama_indikator' => 'Prosentase Klaim Tidak Layak',
            'target_indikator' => '1.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '26',
            'kamus_indikator_id' => '45',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:43:08',
        ],
        [
            'id' => '38',
            'nama_indikator' => 'Kejadian Pasien jatuh pada anak diruang rawat Inap',
            'target_indikator' => '0.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '45',
            'kamus_indikator_id' => '38',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:45:11',
        ],
        [
            'id' => '49',
            'nama_indikator' => 'Kejadian medication error oleh perawat dan bidan di Rumah Sakit Azra',
            'target_indikator' => '1.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '50',
            'kamus_indikator_id' => '49',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:46:47',
        ],
        [
            'id' => '14',
            'nama_indikator' => 'Tidak ada kesalahan input jumlah obat dalam E-Resep oleh dokter spesialis di Poliklinik',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '7',
            'kamus_indikator_id' => '14',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:47:33',
        ],
        [
            'id' => '35',
            'nama_indikator' => 'Angka Kejadian Mesin Hemodialisa Rusak Saat Digunakan',
            'target_indikator' => '0.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '7',
            'kamus_indikator_id' => '35',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:47:59',
        ],
        [
            'id' => '36',
            'nama_indikator' => 'Angka Kejadian Hipotensi Intradialisis',
            'target_indikator' => '20.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '7',
            'kamus_indikator_id' => '36',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:48:10',
        ],
        [
            'id' => '28',
            'nama_indikator' => 'Waktu tunggu Obat di Farmasi (Obat Jadi < 25 menit, Obat Racikan < 55 menit)',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '21',
            'kamus_indikator_id' => '28',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:59:19',
        ],
        [
            'id' => '46',
            'nama_indikator' => 'Kepatuhan Assesmen Akhir Kehidupan pada Pasien Terminal',
            'target_indikator' => '85.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '17',
            'kamus_indikator_id' => '46',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:22:22',
        ],
        [
            'id' => '47',
            'nama_indikator' => 'Angka Ventilator Associated Pnemonia (VAP) di ruang Intensif',
            'target_indikator' => '0.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '17',
            'kamus_indikator_id' => '47',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:22:39',
        ],
        [
            'id' => '61',
            'nama_indikator' => 'Kesesuaian  Pemeriksaan  Laboratorium  sesuai dengan Perjanjian',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '8',
            'kamus_indikator_id' => '61',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:54:05',
        ],
        [
            'id' => '13',
            'nama_indikator' => 'Kepuasan Pasien',
            'target_indikator' => '76.61',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '53',
            'kamus_indikator_id' => '13',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:39:48',
        ],
        [
            'id' => '29',
            'nama_indikator' => 'Kelengkapan berkas Discharge Planning H-1',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '45',
            'kamus_indikator_id' => '29',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:49:44',
        ],
        [
            'id' => '3',
            'nama_indikator' => 'Kepatuhan Identifikasi Pasien',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '50',
            'kamus_indikator_id' => '3',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:35:58',
        ],
        [
            'id' => '25',
            'nama_indikator' => 'Kepatuhan Tatalaksanan Clinical Pathway DHF Anak',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '45',
            'kamus_indikator_id' => '25',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:01:34',
        ],
        [
            'id' => '24',
            'nama_indikator' => 'Kepatuhan Tatalaksana Clinical Pathway Pneumonia / BP Anak',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '45',
            'kamus_indikator_id' => '24',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:03:03',
        ],
        [
            'id' => '12',
            'nama_indikator' => 'Kecepatan Waktu Tanggap Komplain',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '53',
            'kamus_indikator_id' => '12',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:35:40',
        ],
        [
            'id' => '2',
            'nama_indikator' => 'Kepatuhan Penggunaan Alat Pelindung Diri (APD)',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '35',
            'kamus_indikator_id' => '2',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:36:23',
        ],
        [
            'id' => '9',
            'nama_indikator' => 'Kepatuhan Penggunaan Formularium Nasional',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '21',
            'kamus_indikator_id' => '9',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:36:55',
        ],
        [
            'id' => '10',
            'nama_indikator' => 'Kepatuhan Terhadap Clinical Pathway',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '45',
            'kamus_indikator_id' => '10',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:37:37',
        ],
        [
            'id' => '8',
            'nama_indikator' => 'Pelaporan Hasil Kritis Laboratorium',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '8',
            'kamus_indikator_id' => '8',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:40:15',
        ],
        [
            'id' => '4',
            'nama_indikator' => 'Waktu Tanggap Operasi Seksio Sesarea Emergensi < 30 menit',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '44',
            'kamus_indikator_id' => '4',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:41:04',
        ],
        [
            'id' => '32',
            'nama_indikator' => 'Waktu Tunggu Pasien di Instalasi Gawat Darurat',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '18',
            'kamus_indikator_id' => '32',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:50:04',
        ],
        [
            'id' => '22',
            'nama_indikator' => 'Kepatuhan Cuci Tangan 6 langkah',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '35',
            'kamus_indikator_id' => '22',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:51:22',
        ],
        [
            'id' => '48',
            'nama_indikator' => 'Kejadian Iritasi pada Bayi yang dilakukan Fototerapi',
            'target_indikator' => '0.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '55',
            'kamus_indikator_id' => '118',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 04:31:20',
        ],
        [
            'id' => '62',
            'nama_indikator' => 'Kepatuhan Pelaporan Hasil Laboratorium Nilai Kritis',
            'target_indikator' => '90.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '8',
            'kamus_indikator_id' => '62',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '64',
            'nama_indikator' => 'Ketepatan Waktu Menyediakan Makanan Katering',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '3',
            'kamus_indikator_id' => '64',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '65',
            'nama_indikator' => 'Tidak Ada Kesalahan Penempelan Etiket Obat di Farmasi Rawat Jalan',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '21',
            'kamus_indikator_id' => '65',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '66',
            'nama_indikator' => 'Tidak Ada Kesalahan Penulisan Dosis pada Etiket Obat di Farmasi',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '21',
            'kamus_indikator_id' => '66',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '68',
            'nama_indikator' => 'Kelengkapan Laporan Operasi',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '41',
            'kamus_indikator_id' => '68',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '71',
            'nama_indikator' => 'Kejadian Luka Bakar Akibat Tindakan Elektroterapi',
            'target_indikator' => '0.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '29',
            'kamus_indikator_id' => '71',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '72',
            'nama_indikator' => 'Persentase Kepatuhan Kedatangan Pasien Kontrol ke Dokter Spesialis Pasca Reminder',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '37',
            'kamus_indikator_id' => '72',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '73',
            'nama_indikator' => 'Persentase Kesalahan Input Data Identitas Pasien di Bagian Pendaftaran.',
            'target_indikator' => '0.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '37',
            'kamus_indikator_id' => '73',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '74',
            'nama_indikator' => 'Persentase Kesesuaian Booking Online dengan Kehadiran Pasien Rawat Jalan',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '37',
            'kamus_indikator_id' => '74',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '75',
            'nama_indikator' => 'Persentase Akurasi Penentuan Payor Asuransi di Pendaftaran Rawat Jalan',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '37',
            'kamus_indikator_id' => '75',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '82',
            'nama_indikator' => 'Respon Time Menanggapi Kerusakan Alat',
            'target_indikator' => '90.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '6',
            'kamus_indikator_id' => '82',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '83',
            'nama_indikator' => 'Ketepatan Waktu Pemeliharaan Utilitas',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '6',
            'kamus_indikator_id' => '83',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '84',
            'nama_indikator' => 'Angka Keluhan yang Ditindaklanjuti  dari Data Angket Keluhan Terkait Fasilitas',
            'target_indikator' => '90.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '6',
            'kamus_indikator_id' => '84',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '85',
            'nama_indikator' => 'Laporan Harian Internal Terkait Fasillitas',
            'target_indikator' => '90.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '6',
            'kamus_indikator_id' => '85',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '93',
            'nama_indikator' => 'Kepatuhan Ceklis Harian Kendaraan',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '5',
            'kamus_indikator_id' => '93',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '98',
            'nama_indikator' => 'Persentase Proses Rekrutmen Level Staf yang Diselesaikan Tepat Waktu',
            'target_indikator' => '85.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '36',
            'kamus_indikator_id' => '98',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '99',
            'nama_indikator' => 'Ketepatan Waktu Penyusunan dan Review Perjanjian Manajerial (Contract)',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '47',
            'kamus_indikator_id' => '99',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '100',
            'nama_indikator' => 'Waktu Respon Terhadap Permintaan Revisi Dokumen Hukum RS / Perjanjian (Contract) < 72 Jam',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '47',
            'kamus_indikator_id' => '100',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '101',
            'nama_indikator' => 'Kecepatan Waktu Tunggu Perhitungan Pasien RI < 2 Jam',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '30',
            'kamus_indikator_id' => '101',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '102',
            'nama_indikator' => 'Penagihan Klaim Asuransi',
            'target_indikator' => '5.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '52',
            'kamus_indikator_id' => '102',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '103',
            'nama_indikator' => 'Pemantauan Aging Piutang Asuransi',
            'target_indikator' => '10.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '52',
            'kamus_indikator_id' => '103',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '104',
            'nama_indikator' => 'Ketepatan penyajian nilai pendapatan BPJS dalam laporan keuangan',
            'target_indikator' => '30.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '40',
            'kamus_indikator_id' => '104',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '105',
            'nama_indikator' => 'Ketepatan Waktu dalam Penyusunan, Pembayaran dan Pelaporan Pajak',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '40',
            'kamus_indikator_id' => '105',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '106',
            'nama_indikator' => 'Rasio Arus Kas terhadap Pendapatan',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '40',
            'kamus_indikator_id' => '106',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '107',
            'nama_indikator' => 'Ketepatan dalam Pengadaan Logistik Umum',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '28',
            'kamus_indikator_id' => '107',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '109',
            'nama_indikator' => 'Tidak adanya Sterirecord Expired di unit Pelayanan',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '35',
            'kamus_indikator_id' => '109',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '110',
            'nama_indikator' => 'Angka Insiden Petugas Tertusuk Benda Tajam dan Jarum',
            'target_indikator' => '0.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '35',
            'kamus_indikator_id' => '110',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '21',
            'nama_indikator' => 'Tidak ada kesalahan penulisan lokasi operasi di Formulir Serah Terima Perawat di Kamar Operasi',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '27',
            'kamus_indikator_id' => '21',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '53',
            'nama_indikator' => 'Ketersedian alat medis steril untuk tindak pelayanan pasien (Kamar Operasi dan IGD)',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '27',
            'kamus_indikator_id' => '53',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '58',
            'nama_indikator' => 'Pemenuhan Waktu Tunggu Rontgen Thorax Cito < 30 Menit',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '34',
            'kamus_indikator_id' => '58',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '63',
            'nama_indikator' => 'Pemenuhan Waktu Menyiapkan dan Menyajikan Menu < 45 menit',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '3',
            'kamus_indikator_id' => '63',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '79',
            'nama_indikator' => 'Pengisian Angket Kepuasan Pasien Rawat Inap',
            'target_indikator' => '30.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '53',
            'kamus_indikator_id' => '79',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:39:38',
        ],
        [
            'id' => '80',
            'nama_indikator' => 'Peningkatan Rujukan Pasien Luar',
            'target_indikator' => '20.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '54',
            'kamus_indikator_id' => '80',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:40:54',
        ],
        [
            'id' => '81',
            'nama_indikator' => 'Peningkatan Jumlah Pengikut Baru dan Jumlah Interaksi pada Konten yang diposting',
            'target_indikator' => '40.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '54',
            'kamus_indikator_id' => '81',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:41:06',
        ],
        [
            'id' => '69',
            'nama_indikator' => 'Kejadian Drop Out Pasien Terhadap Pelayanan Rehabilitasi Medik dan KTKA',
            'target_indikator' => '0.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '29',
            'kamus_indikator_id' => '69',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:56:36',
        ],
        [
            'id' => '70',
            'nama_indikator' => 'Kesalahan Tindakan Terapi Rehabilitasi Medik dan KTKA yang direncanakan',
            'target_indikator' => '0.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '29',
            'kamus_indikator_id' => '70',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:56:46',
        ],
        [
            'id' => '97',
            'nama_indikator' => 'Persentase Karyawan dengan Jam Pelatihan >20 Jam',
            'target_indikator' => '85.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '36',
            'kamus_indikator_id' => '97',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:59:01',
        ],
        [
            'id' => '86',
            'nama_indikator' => 'Ketepatan Waktu Preventive Alkes',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '6',
            'kamus_indikator_id' => '86',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 09:00:13',
        ],
        [
            'id' => '87',
            'nama_indikator' => 'Respon Time Menanggapi Kerusakan Alkes',
            'target_indikator' => '90.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '6',
            'kamus_indikator_id' => '87',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 09:00:23',
        ],
        [
            'id' => '88',
            'nama_indikator' => 'Angka komplain/ keluhan dari pasien (RI/ RJ) terhadap kebersihan kamar rawat inap, publik area, toilet umum, dan lingkungan rumah sakit (maksimal 15 komplain setiap bulan)',
            'target_indikator' => '0.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '4',
            'kamus_indikator_id' => '88',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 09:02:51',
        ],
        [
            'id' => '89',
            'nama_indikator' => 'Ketersediaan Linen Untuk Pasien Sesuai dengan Parstock Untuk Jumlah Bed yang Tersedia Dalam Waktu 1 x 24 jam',
            'target_indikator' => '90.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '4',
            'kamus_indikator_id' => '89',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 09:03:01',
        ],
        [
            'id' => '90',
            'nama_indikator' => 'Angka Penyelesaian Laporan kasus yang ditangani Security maksimal 3x24 jam sejak penerimaan laporan',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '4',
            'kamus_indikator_id' => '90',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 09:03:12',
        ],
        [
            'id' => '91',
            'nama_indikator' => 'Tidak ada kejadian kehilangan aksesoris kendaraan yang terparkir di RS Azra',
            'target_indikator' => '20.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '4',
            'kamus_indikator_id' => '91',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 09:03:29',
        ],
        [
            'id' => '92',
            'nama_indikator' => 'Ketepatan Jadwal Pengangkutan Limbah B3 Medis di TPS LB3',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '4',
            'kamus_indikator_id' => '92',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 09:03:40',
        ],
        [
            'id' => '95',
            'nama_indikator' => 'Response Time Sopir dalam On Call',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '5',
            'kamus_indikator_id' => '95',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 09:05:59',
        ],
        [
            'id' => '94',
            'nama_indikator' => 'Kepatuhan Security Melaksanakan Patroli',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '5',
            'kamus_indikator_id' => '94',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 09:06:09',
        ],
        [
            'id' => '108',
            'nama_indikator' => 'Ketepatan dalam Pengadaan Sediaan Farmasi',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '28',
            'kamus_indikator_id' => '108',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:19:03',
        ],
        [
            'id' => '78',
            'nama_indikator' => 'Penanganan Langsung Handling Komplain Pasien oleh Masing Masing Unit',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '53',
            'kamus_indikator_id' => '78',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:22:43',
        ],
        [
            'id' => '96',
            'nama_indikator' => 'Penyelesaian terhadap permintaan perbaikan fasilitas SIMRS < 10 menit',
            'target_indikator' => '90.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '23',
            'kamus_indikator_id' => '96',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:28:44',
        ],
        [
            'id' => '1',
            'nama_indikator' => 'Kepatuhan Kebersihan Tangan',
            'target_indikator' => '85.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '35',
            'kamus_indikator_id' => '1',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:36:15',
        ],
        [
            'id' => '11',
            'nama_indikator' => 'Kepatuhan Upaya Pencegahan Risiko Pasien Jatuh',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '45',
            'kamus_indikator_id' => '11',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:38:16',
        ],
        [
            'id' => '77',
            'nama_indikator' => 'Persentase Pemanggilan Kembali (Callback) Terhadap Panggilan yang Tidak Terjawab (Missed Call) di Unit Callcenter',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '37',
            'kamus_indikator_id' => '77',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '111',
            'nama_indikator' => 'Kepatuhan Penempatan Pasien Di Ruang Isolasi Sesuai Indikasi',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '35',
            'kamus_indikator_id' => '111',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '112',
            'nama_indikator' => 'Kepatuhan petugas memilah limbah medis sesuai jenisnya di unit pelayanan',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '35',
            'kamus_indikator_id' => '112',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '113',
            'nama_indikator' => 'Pencatatan Suhu Area Instalasi Gizi',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '35',
            'kamus_indikator_id' => '113',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'id' => '76',
            'nama_indikator' => 'Waktu Tunggu Pelayanan Pendaftaran Pasien Poliklinik Rawat Jalan Dengan Penjaminan Assuransi/Perusahaaan < 15 Menit',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '37',
            'kamus_indikator_id' => '76',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:38:31',
        ],
        [
            'id' => '44',
            'nama_indikator' => 'Prosentase Klaim Pending',
            'target_indikator' => '5.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_kecil',
            'status_indikator' => 'aktif',
            'unit_id' => '26',
            'kamus_indikator_id' => '44',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:42:49',
        ],
        [
            'id' => '50',
            'nama_indikator' => 'Keberhasilan Perawat Dalam Pemasangan Infus satu Kali pada pasien rawat Inap',
            'target_indikator' => '90.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '50',
            'kamus_indikator_id' => '50',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:47:03',
        ],
        [
            'id' => '67',
            'nama_indikator' => 'Kelengkapan Pengisian Informed Concent Setelah Mendapatkan Informasi Yang Jelas',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '41',
            'kamus_indikator_id' => '67',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 08:57:58',
        ],
        [
            'id' => '115',
            'nama_indikator' => 'Kelengkapan PCRA dan ICRA pada setiap Renovasi di RS Azra',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '4',
            'kamus_indikator_id' => '115',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 09:03:51',
        ],
        [
            'id' => '116',
            'nama_indikator' => 'Kecepatan waktu pelaporan kecelakaan kerja staf RS Azra kurang dari 2 x 24 jam',
            'target_indikator' => '90.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '4',
            'kamus_indikator_id' => '116',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 09:04:08',
        ],
        [
            'id' => '117',
            'nama_indikator' => 'Angka keterampilan staf dalam penggunaan APAR',
            'target_indikator' => '80.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '4',
            'kamus_indikator_id' => '117',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-15 09:04:19',
        ],
        [
            'id' => '20',
            'nama_indikator' => 'Tidak ada kesalahan cara pemberian obat elektrolit konsentrat di Rawat Inap dan Intensif',
            'target_indikator' => '100.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '17',
            'kamus_indikator_id' => '20',
            'keterangan' => null,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-04-16 03:56:36',
        ],
        [
            'id' => '118',
            'nama_indikator' => 'BOR (Bed Occupancy Rate)',
            'target_indikator' => '60.00',
            'target_min' => null,
            'target_max' => null,
            'arah_target' => 'lebih_besar',
            'status_indikator' => 'aktif',
            'unit_id' => '41',
            'kamus_indikator_id' => '119',
            'keterangan' => null,
            'created_at' => '2026-01-16 04:02:23',
            'updated_at' => '2026-04-16 04:09:42',
        ],
    ];

        foreach ($indikators as $indikator) {
            DB::table('tbl_indikator')->updateOrInsert(
                ['id' => $indikator['id']],
                [
                    'nama_indikator' => $indikator['nama_indikator'],
                    'target_indikator' => $indikator['target_indikator'],
                    'target_min' => $indikator['target_min'],
                    'target_max' => $indikator['target_max'],
                    'arah_target' => $indikator['arah_target'],
                    'status_indikator' => $indikator['status_indikator'],
                    'unit_id' => $indikator['unit_id'],
                    'kamus_indikator_id' => $indikator['kamus_indikator_id'],
                    'created_at' => $indikator['created_at'],
                    'updated_at' => $indikator['updated_at'],
                ]
            );
        }

        $this->command->info("Seeder Indikator berhasil dijalankan dengan data produksi!");
    }
}
